name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            sudo git pull
            sudo composer install --no-dev --optimize-autoloader
            sudo php artisan config:cache
            sudo php artisan route:cache
            php artisan view:clear
            sudo php artisan migrate --force  # Applique les migrations en production
